non_object_columns = ['multiplayer_cost',
                      'is_high_threat',
                      'unit_size',
                      'health',
                      'mass',
                      'health_per_entity',
                      'run_speed',
                      'fly_speed',
                      'speed',
                      'charge_speed',
                      'flying_charge_speed',
                      'acceleration',
                      'deceleration',
                      'height',
                      'combat_reaction_radius',
                      'hit_reactions_ignore_chance',
                      'knock_interrupts_ignore_chance',
                      'accuracy',
                      'reload',
                      'armour',
                      'parry_chance',
                      'leadership',
                      'is_large',
                      'melee_attack',
                      'melee_defence',
                      'charge_bonus',
                      'damage_mod_flame',
                      'damage_mod_magic',
                      'damage_mod_physical',
                      'damage_mod_missile',
                      'can_skirmish',
                      'ability__Taunt',
                      'ability__My Will Be Done',
                      'ability__Opportunist Murderer',
                      'ability__Portent of Warding',
                      'ability__Ruinous Flesh',
                      'ability__El Syf',
                      'ability__Omen of Hope',
                      'ability__Foe-Seeker',
                      'ability__Get on Wiv it!',
                      'ability__From the Mist',
                      'ability__Call of the Woods',
                      'ability__Soporific Breath',
                      'ability__Too Horrible to Die',
                      'ability__Looming Dread',
                      'ability__The Best Defence',
                      'ability__The Reliquary Binding',
                      'ability__Blizzard Aura',
                      'ability__Something Wicked This Way Comes',
                      'ability__Crowfeast',
                      'ability__Realm of Souls Tier 2',
                      'ability__Dreaded Duellist',
                      'ability__Cold-Blooded',
                      'ability__Bound Fiery Convocation',
                      'ability__Heroic Killing Blow',
                      "ability__Moon Dragon's Breath",
                      'ability__Beastslaver',
                      'ability__Red Fury',
                      'ability__Tricksy Traps',
                      'ability__Bloodgreed',
                      "ability__The Shadow's Coil",
                      'ability__Master Rune of Wrath & Ruin',
                      'ability__Death from Above',
                      'ability__Favour of the Fay',
                      'ability__Berserk',
                      'ability__Martial Mastery',
                      'ability__Rubble & Ruin III',
                      'ability__Hornswaggle',
                      'ability__Master of Beguilement',
                      'ability__Shatter',
                      'ability__Darken the Skies',
                      'ability__Apocalyptic Charge',
                      'ability__Fight or Die!',
                      'ability__Feint & Riposte',
                      "ability__Spearfisher's Net",
                      'ability__Burning Alignment',
                      'ability__Word of Pain',
                      'ability__Lamentation of Despair',
                      'ability__Doppelgang',
                      'ability__Scorch',
                      'ability__"Stay Here, I\'ll Get Help!"',
                      'ability__Dark Venom',
                      'ability__Judgement of the Uxmac',
                      'ability__Loose!',
                      "ability__Assassin's Trophy",
                      "ability__Warrior's Crest",
                      'ability__To the Death',
                      'ability__Copious Vomit',
                      'ability__Verminous Valour',
                      'ability__Smoke Bomb',
                      'ability__Oil Flask',
                      'ability__Thermal Thorax',
                      'ability__Focused Shot',
                      'ability__Pump Harder Ladz!',
                      'ability__Warp Gaze',
                      'ability__Big Boom',
                      'ability__Toad Rage',
                      'ability__High King',
                      'ability__Restore',
                      'ability__Honour or Death',
                      'ability__Wail of Malice',
                      'ability__Bloodroar',
                      'ability__Icon of Devotion',
                      'ability__Monstrous Strength',
                      "ability__Sun Dragon's Breath",
                      'ability__Crumbling',
                      'ability__More Powder!',
                      'ability__Hounds of Orion',
                      'ability__Sacred Guardian',
                      'ability__Blood Oath',
                      'ability__Another Takes its Place',
                      'ability__Black Lotus',
                      'ability__Disintegrating',
                      'ability__Quicksilver Shot',
                      'ability__Billowing Death',
                      'ability__Overwhelming Odour',
                      'ability__The Old Grumblers',
                      'ability__Mislead',
                      'ability__Power Siphon',
                      'ability__Bathed in Blood',
                      'ability__Locus of Hysh',
                      'ability__Seismic Snare',
                      'ability__Venom Wave',
                      'ability__Rune of Hearth & Home',
                      'ability__Primal Instincts',
                      'ability__Unbinding',
                      'ability__Drop Rocks of Sundering',
                      "ability__Gordinar's Dragon Breath",
                      'ability__Soul Eater',
                      'ability__Supreme Shield of the Old Ones',
                      'ability__The Trial of Blades',
                      'ability__Gyrobomber Bomb',
                      'ability__Ghoul King of Ushoran',
                      'ability__Shield of the Old Ones',
                      'ability__Spirit Conduit',
                      'ability__Dark Fire of Chaos',
                      'ability__Curse of Khsar',
                      "ability__Smash 'Em Faster",
                      'ability__Blessing of Asaph',
                      'ability__Pestilential Breath',
                      'ability__Snare-Net',
                      'ability__Blooood!',
                      "ability__Giant Explodin' Spores",
                      'ability__Marked by Ulthar',
                      'ability__Rune of Wrath & Ruin',
                      'ability__Beloved Son of Bretonnia',
                      "ability__The Lady's Champion",
                      'ability__Arcane Configuration',
                      'ability__Grand Shield of Faith',
                      'ability__Aura of Protection',
                      'ability__Aura of Ardour',
                      'ability__Ballistics Calibration',
                      'ability__Miasma of Despair',
                      "ability__Da Boss' Loons",
                      'ability__Unyielding Will',
                      'ability__Scurry Away!',
                      'ability__Evasion',
                      'ability__Guardian',
                      'ability__Skyhammer Bomb',
                      'ability__Prey of Anath Raema',
                      'ability__Mither',
                      'ability__Barbed Net',
                      'ability__Grim Discipline',
                      'ability__Apocalyptic Vision',
                      'ability__Drop Rocks',
                      'ability__The Reliquary Corruption',
                      'ability__Sandstorm',
                      'ability__Deadly Onslaught',
                      'ability__Gaseous Demise',
                      'ability__Wrath of the Creator',
                      'ability__Wrath of Ptra',
                      'ability__Helping Hand',
                      'ability__Squigs Go Wild',
                      'ability__Covenant of Power',
                      'ability__Pestilent Breath',
                      'ability__Soulblight',
                      'ability__Fermented Fungi',
                      'ability__Mighty Roar',
                      'ability__Lightning Reflexes',
                      'ability__Kaboom!',
                      'ability__Crush the Weak',
                      'ability__Murderous Mastery',
                      'ability__Strength of the Penitent',
                      'ability__Song of Enthrallment',
                      'ability__Greater Arcane Conduit',
                      'ability__Master of the Black Arts',
                      'ability__Grombrindal Has No Fear',
                      'ability__Black Nimbus',
                      'ability__Drop Sphere of Tepok',
                      'ability__Drop Rocks of Chotec',
                      'ability__Giver of Glory',
                      'ability__The Liber Mortis',
                      'ability__Hawkish Precision',
                      'ability__Storm of Blades',
                      'ability__Reaper of Souls',
                      'ability__The Hunger',
                      'ability__Focus Instincts',
                      'ability__Heroic Fortitude',
                      'ability__Spite of Da Bad Moon',
                      'ability__The Chilling Aura',
                      'ability__Arcane Conduit',
                      'ability__Rally!',
                      'ability__Noxious Breath',
                      'ability__Volley of High Arrows',
                      'ability__Soul Stealer',
                      'ability__Mad Cap Mushrooms',
                      'ability__Dolorous Blade',
                      "ability__Deathmaster's Sigil",
                      'ability__Seduction',
                      'ability__Fury of Khaine',
                      'ability__Grim Resolve',
                      'ability__Dread Aversion',
                      'ability__Woven Mist',
                      'ability__Strength Through Spite',
                      'ability__The Eye of Kurnous',
                      'ability__Trophy Heads',
                      'ability__Lord of Undeath',
                      'ability__Frenzy',
                      "ability__Get Back 'Ere!",
                      'ability__Emberstorm',
                      'ability__Vigour Mortis',
                      'ability__Spirit Leech',
                      'ability__Grand Hammer of Sigmar',
                      'ability__Strength in Numbers',
                      'ability__Murderous Prowess Indicator',
                      'ability__Wraith Storm',
                      'ability__The Curse of Anraheir',
                      'ability__The Blessing of the Lady',
                      'ability__Gaze of Malice',
                      'ability__Enchanting Beauty',
                      'ability__Banner of Avelorn',
                      'ability__Rune of Negation',
                      'ability__Immortal Will',
                      'ability__Stand Your Ground!',
                      'ability__Death Shriek',
                      'ability__Curse of Djaf',
                      'ability__The Ruination of Cities',
                      'ability__Abyssal Howl',
                      'ability__Blinding Radiance',
                      'ability__Patch Up',
                      'ability__Unholy Vigour',
                      'ability__Fiery Rebirth',
                      'ability__Grand Soulfire',
                      'ability__Benediction',
                      'ability__Bomb-Throw',
                      'ability__Entrenchment',
                      'ability__Ark of Sotek',
                      'ability__Dragonhorn',
                      'ability__Chain Lightning',
                      "ability__Shem's Burning Gaze",
                      'ability__Spirit-Essence of Chaos',
                      'ability__Unholy Clamour',
                      'ability__Rubble & Ruin II',
                      'ability__Balefire',
                      'ability__Bloodstorm',
                      'ability__Blessing of the Ancients',
                      'ability__Flash Bomb',
                      'ability__Unbound',
                      'ability__Concealment Bombs',
                      "ability__Slaughterer's Call",
                      'ability__Bloodshield of Khaine',
                      'ability__Lance',
                      'ability__Frost Breath',
                      'ability__Unholy Lodestone',
                      'ability__Volley of Dark Arrows',
                      'ability__The Rats Emerge',
                      'ability__Forgefire',
                      'ability__Deathblow',
                      "ability__Gotrek's Doom",
                      'ability__Revivification Crystal',
                      'ability__Divine Power',
                      'ability__Halo of Maidenly Wrath',
                      'ability__Refuse to Die',
                      'ability__Hunter of Champions',
                      "ability__Loec's Shroud",
                      'ability__Rowdy',
                      "ability__Manann's Luck",
                      'ability__Rune of Oath & Steel',
                      'ability__Gyrocopter Bomb',
                      'ability__Rabble-Rouse',
                      "ability__Tz'arkan",
                      'ability__Stone Shaper',
                      'ability__Enchanted Ballistics',
                      'ability__Whiplash!',
                      'ability__Doomrocket',
                      'ability__The Wildfire Aura',
                      "ability__Hawk's Talon",
                      'ability__Poisoned',
                      "ability__The Daemon's Curse",
                      'ability__Attuned to Magic',
                      'ability__Red Ruin',
                      "ability__Wurrzag's Revenge",
                      'ability__Wake of Fire',
                      'ability__The Blood Price',
                      'ability__Cackle Fruit',
                      'ability__Rubble & Ruin I',
                      'ability__Soulfire',
                      'ability__All Hands Hoay!',
                      "ability__'Effagee' of da Git",
                      'ability__Emergency Vent',
                      'ability__Brass Orb',
                      'ability__Sacred Spawning of Xhotl',
                      'ability__Fiery Breath',
                      'ability__Lord of the Storm',
                      'ability__Exploding Unit',
                      "ability__Isha's Rain",
                      "ability__Hunter's Call",
                      'ability__Claws of Mourkain',
                      'ability__Duck & Weave',
                      'ability__They Needs Stabbin’',
                      'ability__Dark Protection',
                      'ability__Merciless Slaver',
                      'ability__Blasphemous Tome',
                      'ability__Mist of the Lady',
                      'ability__Oppressive Fighter',
                      'ability__Aura of the Lady',
                      'ability__Banishment',
                      'ability__Arrow of Kurnous',
                      'ability__Arrow of Aqshy',
                      'ability__Shield of Chaqua',
                      'ability__Aura of Dark Grandeur',
                      'ability__Unholy Power',
                      'ability__Slippery',
                      'ability__Blood Frenzy',
                      'ability__The Curse',
                      'ability__Swamp Breath',
                      "ability__Hunter's Snare",
                      'ability__The Flag of Blood Keep',
                      'ability__Accusation',
                      'ability__Aura of Pestilence',
                      "ability__You're Next!",
                      'ability__Call of Violence',
                      'ability__Oath of Vengeance',
                      'ability__Fleur de Lys Banner',
                      'ability__Guardians of the Wildwood',
                      'ability__Gaze of Khaine',
                      'ability__Hold the Line!',
                      'ability__Shield of Faith',
                      'ability__Best of Da Best',
                      "ability__Da Great 'Un Iz 'Ere!",
                      'ability__Stand or Die!',
                      'ability__Master of the Dead',
                      "ability__Star Dragon's Breath",
                      'ability__Abandon Ship!',
                      'ability__Blood Lust',
                      'ability__Maternal Instinct',
                      'ability__Storm of the Night',
                      'ability__Martial Prowess',
                      'ability__Ghosts of the Past',
                      'ability__Noxious Disintegration',
                      'ability__Realm of Souls Tier 3',
                      "ability__The Lion's Shield",
                      'ability__Master Rune of Negation',
                      'ability__Warp-Quake',
                      'ability__Net of Amyntok',
                      'ability__Reanimate',
                      'ability__Revenge Incarnate',
                      'ability__Shield of Thorns',
                      'ability__Seafang',
                      'ability__Witchbrew',
                      'ability__Aura of Agony',
                      'ability__Wall of Unholy Sound',
                      'ability__Enrage',
                      'ability__Arachneruption',
                      'ability__Dark Benediction',
                      'ability__Swiftness of Itzl',
                      'ability__Liquid Fortification',
                      'ability__Locus of Power',
                      'ability__Dead Eyes',
                      'ability__Black Scythes',
                      'ability__Potion of Charoi',
                      'ability__Warpaint of Wurrzag',
                      'ability__Rok of Itza',
                      'ability__Boom!',
                      "ability__Tretch's Raiders",
                      'ability__Mighty Oath Stone',
                      'ability__Magical Void',
                      'ability__Fleet-Footed',
                      'ability__Murderous Prowess',
                      'ability__Regeneration',
                      'ability__Lord of Dragons',
                      'ability__Master Rune of Oath & Steel',
                      'ability__Primal Rage',
                      'ability__Soul Devourer',
                      'ability__Master of the Skies',
                      "ability__Shackolot's Noxious Breath",
                      'ability__Favour of the Ruinous Powers',
                      'ability__Primal Roar',
                      'ability__Realm of Souls Tier 1',
                      'ability__Magical Animus',
                      'ability__Primal Fury',
                      'ability__The Loons of Eight Peaks',
                      'ability__Spirit of the Tempest',
                      'ability__Power of the Dragonback',
                      'ability__Rage',
                      'ability__Rock Bottom',
                      'ability__Unlimited Power!',
                      'ability__Undeath Resurgent',
                      'ability__Squigs Go Boom',
                      'ability__Extra Powder',
                      'ability__Heart Piercing',
                      'ability__Spinning Loons',
                      'ability__Language of Da Boyz',
                      'ability__Hail of Fire',
                      'ability__Spirit of Gork (or Mork)',
                      'ability__Boon of Isha',
                      "ability__Don't Even Try It",
                      'ability__Hammer of Sigmar',
                      "ability__Mistwalkers' Barrage",
                      'ability__Lesser Doombolt',
                      'ability__Tombstrike',
                      'ability__Swarm of Flies',
                      'ability__Rebirth',
                      'attribute__undead',
                      'attribute__expendable',
                      'attribute__rampage',
                      'attribute__snipe',
                      'attribute__strider',
                      'attribute__construct',
                      'attribute__encourages',
                      'attribute__guerrilla_deploy',
                      'attribute__stalk',
                      'attribute__causes_fear',
                      'attribute__immune_to_psychology',
                      'attribute__cant_run',
                      'attribute__ignore_trees',
                      'attribute__hide_forest',
                      'attribute__fatigue_immune',
                      'attribute__unbreakable',
                      'attribute__causes_terror',
                      'attribute__charge_reflector',
                      'attribute__wallbreaker',
                      'attribute__charge_reflector_vs_large',
                      'attribute__mounted_fire_move',
                      'melee__ignition_amount',
                      'melee__is_magical',
                      'melee__base_damage',
                      'melee__ap_damage',
                      'melee__ap_ratio',
                      'melee__bonus_v_large',
                      'melee__bonus_v_infantry',
                      'melee__splash_attack_max_attacks',
                      'melee__splash_attack_power_multiplier',
                      'melee__weapon_length',
                      'melee__collision_attack_max_targets',
                      'melee__collision_attack_max_targets_cooldown',
                      'melee__melee_attack_interval',
                      'melee__damage',
                      'missile_primary__damage',
                      'missile_primary__reload_time',
                      'missile_primary__total_accuracy',
                      'missile_primary__ammo',
                      'missile_secondary__damage',
                      'missile_secondary__reload_time',
                      'missile_secondary__total_accuracy',
                      'missile_secondary__ammo',
                      'missile_secondary__ignition_amount',
                      'missile_primary__ignition_amount',
                      'missile_primary__is_magical']

category_columns = ['weight',
                    'group_name',
                    'melee__splash_attack_target_size',
                    'melee__phase',
                    'missile_primary__phase',
                    'missile_secondary__phase']
